version: '3.8'
name: 'anti-bruteforce'

services:
  app:
    build:
      dockerfile: ./build/Dockerfile_app
      context: ../
    depends_on:
      - postgres
      - redis
    restart: on-failure
    networks:
      - anti-bruteforce-network
  postgres:
    container_name: db_antibruteforce
    image: postgres:15
    build:
      context: ../
    environment:
      POSTGRES_DB: "antibruteforce"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5430:5432"
    restart: unless-stopped
    volumes:
      - ./../data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - anti-bruteforce-network
  redis:
    image: redis:7
    restart: always
    container_name: redis-${COMPOSE_PROJECT_NAME}
    networks:
      - anti-bruteforce-network
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./../data/redis:/usr/local/etc/redis/redis.conf

networks:
  anti-bruteforce-network:
    driver: bridge