logger:
  level: DEBUG

grpsServer:
  port: 50051
  host: antibruteforce

psql:
  dsn: "host=localhost port=5430 user=user password=qwerty dbname=antibruteforce sslmode=disable"
  migration: migrations

redis:
  port: 6380
  host: 127.0.0.1
  db: 0
  tokenDb: 1